@echo off
echo Starting TipScribe Development Server...
echo.
echo Checking Node.js version...
node --version
echo.
echo Checking npm version...
npm --version
echo.
echo Setting environment variables...
set NODE_ENV=development
set PORT=5000
echo.
echo Starting server with tsx...
npx tsx server/index.ts